security:
  oauth2:
    client:
      client-id: foo
      client-secret: bar
    resource:
      token-info-uri: http://192.168.40.146:8080/oauth/check_token
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080
